import assert from 'node:assert/strict';
import JSZip from 'jszip';
import {analyzeGlyphs} from '../src/pdf/textLayout';
import {pagesToDocx} from '../src/pdf/docxBuild';
import type {TextGlyph,PdfRuling} from '../src/pdf/textTypes';

const glyph=(str:string,x:number,y:number,size=12,extra:Partial<TextGlyph>={}):TextGlyph=>({str,x,y,width:str.length*size*.42,size,eol:false,fontFamily:'Garamond',...extra});
const glyphs=[glyph('Item',50,700,16,{bold:true,fontFamily:'Cambria'}),glyph('Amount',275,700,16,{bold:true,fontFamily:'Cambria'}),glyph('First line',50,650,12,{italic:true}),glyph('Second line',50,630),glyph('125.00',275,650),glyph('900.00',275,575)];
const rulings:PdfRuling[]=[...[40,260,450].map(x=>({x1:x,x2:x,y1:560,y2:720})),...[720,680,600,560].map(y=>({x1:40,x2:450,y1:y,y2:y}))];
const blocks=analyzeGlyphs(glyphs,600,800,rulings);
const table=blocks.find(block=>block.kind==='table');
assert.ok(table?.kind==='table');
assert.deepEqual(table.rows,[['Item','Amount'],['First line\nSecond line','125.00'],['','900.00']]);
assert.deepEqual(table.columnWidthsPt,[220,190]);
assert.deepEqual(table.rowHeightsPt,[40,80,40]);
assert.equal(table.cellLines?.[0]?.[0]?.[0]?.runs?.[0]?.fontFamily,'Cambria');
assert.equal(table.cellLines?.[1]?.[0]?.[0]?.runs?.[0]?.italic,true);
const bytes=await pagesToDocx([{width:600,height:800,blocks}]);
const xml=await JSZip.loadAsync(bytes).then(zip=>zip.file('word/document.xml')!.async('string'));
assert.ok(xml.includes('w:ascii="Cambria"'));
assert.ok(xml.includes('w:ascii="Garamond"'));
assert.ok(xml.includes('<w:sz w:val="32"/>'));
assert.ok(xml.includes('<w:i/>'));
assert.ok(xml.includes('<w:br/>'));
assert.ok(xml.includes('<w:trHeight w:val="1600" w:hRule="atLeast"/>'));
const borderless=analyzeGlyphs(glyphs.slice(0,5).map((glyph,i)=>({...glyph,y:[700,700,680,666,680][i]!})),600,800).find(block=>block.kind==='table');
assert.ok(borderless?.kind==='table' && borderless.cellLines?.[0]?.[0]?.[0]?.runs?.[0]?.fontSize===16);
const columns=await pagesToDocx([{width:600,height:800,blocks:[{kind:'para',heading:true,x:40,xEnd:560,top:760,bottom:744,lines:[{text:'A heading wider than the columns',fontSize:16}]},{kind:'columns',x:40,widthsPt:[160,180],columns:[[{kind:'para',heading:false,x:40,lines:[{text:'Left',fontSize:12}]}],[{kind:'para',heading:false,x:200,lines:[{text:'Right',fontSize:12}]}]]}]}]);
const columnXml=await JSZip.loadAsync(columns).then(zip=>zip.file('word/document.xml')!.async('string'));
assert.ok(columnXml.includes('<w:gridCol w:w="3200"/><w:gridCol w:w="3600"/>'));
console.log('PDF_WORD_FIDELITY_OK styled cells, multiline rows, empty cells, grid dimensions, borderless styles and original column widths');
