#!/usr/bin/env python3
"""Generate the deterministic, non-confidential PDF used in Play screenshots."""

from __future__ import annotations

import argparse
from pathlib import Path
import tempfile

from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import A4, landscape
from reportlab.pdfbase.pdfmetrics import stringWidth
from reportlab.pdfgen import canvas


OUTPUT_PATH = Path(__file__).resolve().parent.parent / "fixtures" / "ream-screenshot-fixture.pdf"

INK = HexColor("#211D33")
MUTED = HexColor("#716C82")
PURPLE = HexColor("#6652E8")
BLUE = HexColor("#6F86F4")
TEAL = HexColor("#168F84")
SURFACE = HexColor("#F5F3FA")
CARD = HexColor("#FFFFFF")
LINE = HexColor("#DDD8EA")
SOFT_PURPLE = HexColor("#EEEAFE")
SOFT_TEAL = HexColor("#E3F5F2")


def wrap_text(text: str, font_name: str, font_size: float, width: float) -> list[str]:
    words = text.split()
    lines: list[str] = []
    current = ""
    for word in words:
        candidate = word if not current else f"{current} {word}"
        if stringWidth(candidate, font_name, font_size) <= width:
            current = candidate
        else:
            if current:
                lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines


def draw_wrapped(
    pdf: canvas.Canvas,
    text: str,
    x: float,
    y: float,
    width: float,
    *,
    font_name: str = "Helvetica",
    font_size: float = 10.5,
    leading: float = 15,
    color=INK,
) -> float:
    pdf.setFillColor(color)
    pdf.setFont(font_name, font_size)
    for line in wrap_text(text, font_name, font_size, width):
        pdf.drawString(x, y, line)
        y -= leading
    return y


def draw_page_chrome(
    pdf: canvas.Canvas,
    page_number: int,
    section: str,
    page_size: tuple[float, float],
) -> None:
    width, height = page_size
    pdf.setFillColor(SURFACE)
    pdf.rect(0, 0, width, height, fill=1, stroke=0)
    pdf.setFillColor(PURPLE)
    pdf.roundRect(40, height - 58, 26, 26, 8, fill=1, stroke=0)
    pdf.setFillColor(CARD)
    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawCentredString(53, height - 49, "R")
    pdf.setFillColor(INK)
    pdf.setFont("Helvetica-Bold", 9)
    pdf.drawString(76, height - 43, "REAM SCREENSHOT FIXTURE")
    pdf.setFillColor(MUTED)
    pdf.setFont("Helvetica", 8.5)
    pdf.drawRightString(width - 40, height - 43, section.upper())

    pdf.setStrokeColor(LINE)
    pdf.setLineWidth(0.6)
    pdf.line(40, 35, width - 40, 35)
    pdf.setFillColor(MUTED)
    pdf.setFont("Helvetica", 8)
    pdf.drawString(40, 21, "Synthetic content - safe for product screenshots")
    pdf.drawRightString(width - 40, 21, f"Page {page_number} of 5")


def draw_badge(pdf: canvas.Canvas, text: str, x: float, y: float, width: float) -> None:
    pdf.setFillColor(SOFT_TEAL)
    pdf.roundRect(x, y, width, 24, 12, fill=1, stroke=0)
    pdf.setFillColor(TEAL)
    pdf.setFont("Helvetica-Bold", 8.5)
    pdf.drawCentredString(x + width / 2, y + 8, text)


def draw_bullet(
    pdf: canvas.Canvas,
    text: str,
    x: float,
    y: float,
    width: float,
    *,
    number: int | None = None,
) -> float:
    pdf.setFillColor(PURPLE)
    pdf.circle(x + 6, y + 4, 6, fill=1, stroke=0)
    pdf.setFillColor(CARD)
    pdf.setFont("Helvetica-Bold", 7.5)
    pdf.drawCentredString(x + 6, y + 1.5, str(number) if number is not None else "-")
    return draw_wrapped(pdf, text, x + 20, y + 8, width - 20, font_size=10, leading=14)


def draw_cover(pdf: canvas.Canvas) -> None:
    width, height = A4
    draw_page_chrome(pdf, 1, "Overview", A4)
    draw_badge(pdf, "SYNTHETIC - NON-CONFIDENTIAL - OFFLINE", 40, height - 112, 238)

    pdf.setFillColor(INK)
    pdf.setFont("Helvetica-Bold", 29)
    pdf.drawString(40, height - 166, "A clean document for")
    pdf.setFillColor(PURPLE)
    pdf.drawString(40, height - 201, "real app screenshots")
    draw_wrapped(
        pdf,
        "This deterministic fixture gives Ream realistic text, tables, spacing, and mixed page layouts without exposing personal files.",
        40,
        height - 235,
        440,
        font_size=11.5,
        leading=17,
        color=MUTED,
    )

    card_y = height - 515
    pdf.setFillColor(CARD)
    pdf.setStrokeColor(LINE)
    pdf.setLineWidth(0.7)
    pdf.roundRect(40, card_y, width - 80, 210, 18, fill=1, stroke=1)
    pdf.setFillColor(INK)
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(62, card_y + 177, "Fixture checklist")

    bullets = [
        "Five pages with portrait and landscape orientations.",
        "Headings, paragraphs, numbered steps, and compact callouts.",
        "A ruled data table with numeric and status columns.",
        "Stable sample content that can be regenerated byte-for-byte.",
    ]
    y = card_y + 145
    for index, item in enumerate(bullets, start=1):
        y = draw_bullet(pdf, item, 62, y, width - 124, number=index) - 7

    metric_y = 92
    metric_width = (width - 96) / 3
    for index, (value, label) in enumerate(
        [("5", "sample pages"), ("1", "structured table"), ("0", "personal records")]
    ):
        x = 40 + index * (metric_width + 8)
        pdf.setFillColor(SOFT_PURPLE if index < 2 else SOFT_TEAL)
        pdf.roundRect(x, metric_y, metric_width, 62, 14, fill=1, stroke=0)
        pdf.setFillColor(PURPLE if index < 2 else TEAL)
        pdf.setFont("Helvetica-Bold", 20)
        pdf.drawString(x + 15, metric_y + 30, value)
        pdf.setFont("Helvetica", 8.5)
        pdf.drawString(x + 15, metric_y + 14, label)
    pdf.showPage()


def draw_memo(pdf: canvas.Canvas) -> None:
    width, height = A4
    draw_page_chrome(pdf, 2, "Structured text", A4)
    pdf.setFillColor(INK)
    pdf.setFont("Helvetica-Bold", 23)
    pdf.drawString(40, height - 108, "Product quality memo")
    pdf.setFillColor(MUTED)
    pdf.setFont("Helvetica", 9)
    pdf.drawString(40, height - 128, "REFERENCE: REAM-QA-001")
    pdf.drawRightString(width - 40, height - 128, "STATUS: READY FOR REVIEW")

    pdf.setStrokeColor(LINE)
    pdf.line(40, height - 145, width - 40, height - 145)

    y = height - 178
    pdf.setFillColor(PURPLE)
    pdf.setFont("Helvetica-Bold", 13)
    pdf.drawString(40, y, "Purpose")
    y = draw_wrapped(
        pdf,
        "Use a repeatable document when reviewing PDF reading, page organization, and PDF to Word reconstruction. Every sentence is intentionally generic and safe to display.",
        40,
        y - 23,
        width - 80,
        font_size=10.5,
        leading=16,
    ) - 15

    pdf.setFillColor(PURPLE)
    pdf.setFont("Helvetica-Bold", 13)
    pdf.drawString(40, y, "Review workflow")
    y -= 30
    steps = [
        "Open this fixture from Ream's PDF reader and confirm page controls remain visible.",
        "Search for the phrase structured table and verify the correct page is found.",
        "Open Organize, wait for all five thumbnails, then rotate one page and undo it.",
        "Run PDF to Word and compare headings, paragraph spacing, table borders, and page orientation.",
    ]
    for index, step in enumerate(steps, start=1):
        y = draw_bullet(pdf, step, 40, y, width - 80, number=index) - 9

    callout_y = 122
    pdf.setFillColor(SOFT_PURPLE)
    pdf.roundRect(40, callout_y, width - 80, 78, 14, fill=1, stroke=0)
    pdf.setFillColor(PURPLE)
    pdf.setFont("Helvetica-Bold", 10)
    pdf.drawString(58, callout_y + 53, "EXPECTED RESULT")
    draw_wrapped(
        pdf,
        "The interface stays calm and readable while every action remains obvious, reversible, and reachable from persistent navigation.",
        58,
        callout_y + 34,
        width - 116,
        font_size=10,
        leading=14,
    )
    pdf.showPage()


def draw_table(pdf: canvas.Canvas) -> None:
    width, height = A4
    draw_page_chrome(pdf, 3, "Structured table", A4)
    pdf.setFillColor(INK)
    pdf.setFont("Helvetica-Bold", 23)
    pdf.drawString(40, height - 108, "Sample inventory table")
    draw_wrapped(
        pdf,
        "A ruled table for checking row detection, wrapped cells, numeric alignment, and status labels.",
        40,
        height - 133,
        width - 80,
        font_size=10,
        leading=14,
        color=MUTED,
    )

    rows = [
        ("Fixture cover", "Document", "1", "$0.00", "Ready"),
        ("Quality memo", "Text", "2", "$0.00", "Ready"),
        ("Inventory table", "Table", "3", "$0.00", "Review"),
        ("Two-column guide", "Layout", "4", "$0.00", "Ready"),
        ("Operations summary", "Landscape", "5", "$0.00", "Review"),
        ("Synthetic non-confidential screenshot archive", "Privacy", "0 files", "$0.00", "Private"),
    ]
    headers = ("Item", "Category", "Page", "Cost", "Status")
    x_positions = [40, 230, 342, 400, 476]
    column_widths = [190, 112, 58, 76, 79]
    top = height - 190
    row_height = 49

    pdf.setFillColor(PURPLE)
    pdf.roundRect(40, top - 34, width - 80, 34, 10, fill=1, stroke=0)
    pdf.setFillColor(CARD)
    pdf.setFont("Helvetica-Bold", 9)
    for index, header in enumerate(headers):
        if index in (2, 3):
            pdf.drawRightString(x_positions[index] + column_widths[index] - 10, top - 22, header)
        else:
            pdf.drawString(x_positions[index] + 10, top - 22, header)

    for row_index, row in enumerate(rows):
        row_top = top - 34 - row_index * row_height
        pdf.setFillColor(CARD if row_index % 2 == 0 else HexColor("#FAF9FD"))
        pdf.setStrokeColor(LINE)
        pdf.rect(40, row_top - row_height, width - 80, row_height, fill=1, stroke=1)
        for cell_index, cell in enumerate(row):
            x = x_positions[cell_index]
            pdf.setFillColor(INK if cell_index != 4 else (TEAL if cell in ("Ready", "Private") else PURPLE))
            font_name = "Helvetica-Bold" if cell_index in (0, 4) else "Helvetica"
            font_size = 9.2
            pdf.setFont(font_name, font_size)
            if cell_index in (2, 3):
                pdf.drawRightString(x + column_widths[cell_index] - 10, row_top - 29, cell)
            else:
                cell_lines = wrap_text(cell, font_name, font_size, column_widths[cell_index] - 20)
                baseline = row_top - (22 if len(cell_lines) > 1 else 29)
                for line_index, line in enumerate(cell_lines):
                    pdf.drawString(x + 10, baseline - line_index * 12, line)

    table_bottom = top - 34 - len(rows) * row_height
    pdf.setLineWidth(0.6)
    for separator_x in x_positions[1:]:
        pdf.setStrokeColor(HexColor("#8B79F2"))
        pdf.line(separator_x, top - 34, separator_x, top)
        pdf.setStrokeColor(LINE)
        pdf.line(separator_x, table_bottom, separator_x, top - 34)

    note_y = table_bottom - 80
    pdf.setFillColor(SOFT_TEAL)
    pdf.roundRect(40, note_y, width - 80, 64, 13, fill=1, stroke=0)
    pdf.setFillColor(TEAL)
    pdf.setFont("Helvetica-Bold", 9.5)
    pdf.drawString(56, note_y + 40, "TABLE NOTE")
    draw_wrapped(
        pdf,
        "All values are fictional. The zero cost and generic labels prevent accidental disclosure or misleading commercial claims.",
        56,
        note_y + 22,
        width - 112,
        font_size=9.2,
        leading=13,
    )
    pdf.showPage()


def draw_columns(pdf: canvas.Canvas) -> None:
    width, height = A4
    draw_page_chrome(pdf, 4, "Columns and lists", A4)
    pdf.setFillColor(INK)
    pdf.setFont("Helvetica-Bold", 23)
    pdf.drawString(40, height - 108, "Two-column extraction guide")

    gutter = 24
    column_width = (width - 80 - gutter) / 2
    left_x = 40
    right_x = 40 + column_width + gutter
    top = height - 155
    pdf.setStrokeColor(LINE)
    pdf.line(width / 2, top + 4, width / 2, 110)

    pdf.setFillColor(PURPLE)
    pdf.setFont("Helvetica-Bold", 12.5)
    pdf.drawString(left_x, top, "Readable hierarchy")
    y = draw_wrapped(
        pdf,
        "Clear headings, short paragraphs, and consistent spacing help readers scan before they commit to an action.",
        left_x,
        top - 24,
        column_width,
        font_size=10.2,
        leading=15,
    ) - 16
    for number, text in enumerate(
        [
            "Start with the task outcome.",
            "Keep the primary action visually dominant.",
            "Place destructive actions away from routine controls.",
            "Confirm completion with useful, specific feedback.",
        ],
        start=1,
    ):
        y = draw_bullet(pdf, text, left_x, y, column_width, number=number) - 9

    pdf.setFillColor(PURPLE)
    pdf.setFont("Helvetica-Bold", 12.5)
    pdf.drawString(right_x, top, "Extraction cues")
    y = draw_wrapped(
        pdf,
        "This column intentionally uses different content so a converter must preserve reading order instead of merging lines across the gutter.",
        right_x,
        top - 24,
        column_width,
        font_size=10.2,
        leading=15,
    ) - 16

    cues = [
        ("Typography", "Bold section titles with regular explanatory text."),
        ("Spacing", "Visible separation between ideas and controls."),
        ("Navigation", "Five persistent destinations with stable labels."),
        ("Motion", "Subtle transitions that respect reduced-motion settings."),
    ]
    for label, description in cues:
        pdf.setFillColor(CARD)
        pdf.setStrokeColor(LINE)
        pdf.roundRect(right_x, y - 55, column_width, 52, 12, fill=1, stroke=1)
        pdf.setFillColor(PURPLE)
        pdf.setFont("Helvetica-Bold", 9.5)
        pdf.drawString(right_x + 12, y - 21, label)
        draw_wrapped(
            pdf,
            description,
            right_x + 12,
            y - 37,
            column_width - 24,
            font_size=8.7,
            leading=12,
            color=MUTED,
        )
        y -= 65
    pdf.showPage()


def draw_landscape(pdf: canvas.Canvas) -> None:
    page_size = landscape(A4)
    pdf.setPageSize(page_size)
    width, height = page_size
    draw_page_chrome(pdf, 5, "Landscape summary", page_size)
    pdf.setFillColor(INK)
    pdf.setFont("Helvetica-Bold", 22)
    pdf.drawString(40, height - 105, "Landscape operations summary")
    pdf.setFillColor(MUTED)
    pdf.setFont("Helvetica", 10)
    pdf.drawString(40, height - 128, "A wide page for mixed-orientation rendering and conversion checks.")

    cards = [
        ("Scan", "Ready", "Camera intake"),
        ("Extract", "Ready", "Text and tables"),
        ("Organize", "Ready", "Reorder and rotate"),
        ("Export", "Review", "PDF and DOCX"),
    ]
    card_width = (width - 104) / 4
    card_y = height - 238
    for index, (label, status, detail) in enumerate(cards):
        x = 40 + index * (card_width + 8)
        pdf.setFillColor(CARD)
        pdf.setStrokeColor(LINE)
        pdf.roundRect(x, card_y, card_width, 82, 14, fill=1, stroke=1)
        pdf.setFillColor(PURPLE)
        pdf.setFont("Helvetica-Bold", 12)
        pdf.drawString(x + 14, card_y + 55, label)
        pdf.setFillColor(TEAL if status == "Ready" else PURPLE)
        pdf.setFont("Helvetica-Bold", 8)
        pdf.drawRightString(x + card_width - 14, card_y + 56, status.upper())
        pdf.setFillColor(MUTED)
        pdf.setFont("Helvetica", 8.7)
        pdf.drawString(x + 14, card_y + 25, detail)

    table_top = card_y - 42
    widths = [180, 120, 115, 125, 125]
    headers = ["Check", "Owner", "Evidence", "Result", "Next action"]
    rows = [
        ["Navigation", "Product", "5 destinations", "Pass", "Keep stable"],
        ["Focus visibility", "Accessibility", "3 px outline", "Pass", "Re-test"],
        ["Store graphics", "Release", "Automated verifier", "Pass", "Upload"],
        ["Android screenshots", "Publisher", "Real device capture", "Pending", "Capture"],
    ]
    x_positions = [40]
    for column_width in widths[:-1]:
        x_positions.append(x_positions[-1] + column_width)

    pdf.setFillColor(PURPLE)
    pdf.roundRect(40, table_top - 31, sum(widths), 31, 9, fill=1, stroke=0)
    pdf.setFillColor(CARD)
    pdf.setFont("Helvetica-Bold", 8.5)
    for index, header in enumerate(headers):
        pdf.drawString(x_positions[index] + 9, table_top - 20, header)

    row_height = 37
    for row_index, row in enumerate(rows):
        row_y = table_top - 31 - (row_index + 1) * row_height
        pdf.setFillColor(CARD if row_index % 2 == 0 else HexColor("#FAF9FD"))
        pdf.setStrokeColor(LINE)
        pdf.rect(40, row_y, sum(widths), row_height, fill=1, stroke=1)
        for cell_index, cell in enumerate(row):
            pdf.setFillColor(TEAL if cell == "Pass" else (PURPLE if cell == "Pending" else INK))
            pdf.setFont("Helvetica-Bold" if cell_index in (0, 3) else "Helvetica", 8.4)
            pdf.drawString(x_positions[cell_index] + 9, row_y + 14, cell)

    pdf.showPage()


def generate(output_path: Path = OUTPUT_PATH) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    pdf = canvas.Canvas(
        str(output_path),
        pagesize=A4,
        # Leave content streams uncompressed so byte-for-byte CI verification
        # does not depend on the runner's zlib implementation.
        pageCompression=0,
        invariant=1,
    )
    pdf.setTitle("Ream Screenshot Fixture")
    pdf.setAuthor("Ream")
    pdf.setSubject("Synthetic non-confidential content for Android store screenshots")
    pdf.setKeywords("Ream, PDF, screenshot, fixture, synthetic")
    draw_cover(pdf)
    draw_memo(pdf)
    draw_table(pdf)
    draw_columns(pdf)
    draw_landscape(pdf)
    pdf.save()
    return output_path


def verify_committed_fixture() -> None:
    if not OUTPUT_PATH.is_file():
        raise SystemExit(f"Committed fixture is missing: {OUTPUT_PATH}")

    with tempfile.TemporaryDirectory(prefix="ream-screenshot-fixture-") as temp_dir:
        candidate = Path(temp_dir) / OUTPUT_PATH.name
        generate(candidate)
        expected_bytes = OUTPUT_PATH.read_bytes()
        candidate_bytes = candidate.read_bytes()

    if candidate_bytes != expected_bytes:
        raise SystemExit(
            "Committed screenshot fixture does not match the deterministic generator. "
            "Regenerate it with this script and review every rendered page."
        )
    print(f"SCREENSHOT_FIXTURE_OK bytes={len(expected_bytes)} path={OUTPUT_PATH}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Regenerate to a temporary path and byte-compare with the committed fixture.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=OUTPUT_PATH,
        help="Output path when generating (defaults to the committed fixture).",
    )
    args = parser.parse_args()

    if args.check:
        verify_committed_fixture()
        return
    print(generate(args.output.resolve()))


if __name__ == "__main__":
    main()
